<?php
/**
 * The template for displaying the settings page.
 *
 * @since 0.1.0
 * @change 0.2.0 - Added option for ignoring admins.
 *
 * @global array $options Plugin Settings array.
 *
 * @package Integrate Umami
 */

?>
<form method="post" action="options.php" xmlns="http://www.w3.org/1999/html">
	<?php settings_fields( 'integrate_umami' ); ?>
	<table class="form-table">
		<tr>
			<th scope="row">
				<?php esc_html_e( 'Enabled', 'integrate-umami' ); ?>
			</th>
			<td>
				<label for="integrate_umami_enabled">
					<input type="checkbox" name="integrate_umami_options[enabled]" id="integrate_umami_enabled"
						value="1" <?php checked( $options['enabled'] ); ?> />
					<?php esc_html_e( 'Enable umami analytics', 'integrate-umami' ); ?>
				</label>
			</td>
		</tr>

		<tr>
			<th scope="row">
				<?php esc_html_e( 'Script Url', 'integrate-umami' ); ?>
			</th>
			<td>
				<input class="integrate-umami-url" type="url" name="integrate_umami_options[script_url]" id="integrate_umami_script_url"
					value="<?php echo esc_attr( $options['script_url'] ); ?>"/>
				<p class="description">
					<?php
					echo wp_kses(
						__( 'The URL to your Umami tracking script.<br>Self-hosted: typically <code>https://your-domain.com/script.js</code><br>Umami Cloud: use <code>https://cloud.umami.is/script.js</code>', 'integrate-umami' ),
						array(
							'br'   => array(),
							'code' => array(),
						)
					);
					?>
				</p>
			</td>
		</tr>

		<tr>
			<th scope="row">
				<?php esc_html_e( 'Website ID', 'integrate-umami' ); ?>
			</th>
			<td>
				<input class="integrate-umami-text"  type="text" name="integrate_umami_options[website_id]" id="integrate_umami_website_id"
					value="<?php echo esc_attr( $options['website_id'] ); ?>"/>
				<p class="description"><?php esc_html_e( 'The umami websiteId generated by your installation', 'integrate-umami' ); ?></p>
			</td>
		</tr>
	</table>

	<div class="integrate-umami-collapsed">
		<input class="toggle" id="advanced-options" type="checkbox">
		<label class="toggle-label" for="advanced-options"><?php esc_html_e( 'Advanced Options', 'integrate-umami' ); ?></label>
		<div class="content">
			<table class="form-table">
				<tr>
					<th scope="row">
						<?php esc_html_e( 'Host Url', 'integrate-umami' ); ?>
					</th>
					<td>
						<input class="integrate-umami-url" type="url" name="integrate_umami_options[host_url]" id="integrate_umami_host_url"
							value="<?php echo esc_attr( $options['host_url'] ); ?>"/>
						<p class="description">
						<?php
						echo wp_kses(
							__( 'The URL of the Umami instance <b>if it is different from the URL to the script.</b>', 'integrate-umami' ),
							array(
								'b' => array(),
							)
						);
						?>
						</p>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Use Host Url', 'integrate-umami' ); ?>
					</th>
					<td>
						<label for="integrate_umami_use_host_url">
							<input type="checkbox" name="integrate_umami_options[use_host_url]" id="integrate_umami_use_host_url"
								value="1" <?php checked( $options['use_host_url'] ); ?> />
							<?php
							echo wp_kses(
								__( 'Use Host Url as data target. <a href="https://umami.is/docs/tracker-configuration">More information</a>', 'integrate-umami' ),
								array(
									'a' => array(
										'href' => array(),
									),
								)
							);
							?>
						</label>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Ignore Admins', 'integrate-umami' ); ?>
					</th>
					<td>
						<label for="integrate_umami_ignore_admins">
							<input type="checkbox" name="integrate_umami_options[ignore_admins]" id="integrate_umami_ignore_admins"
								value="1" <?php checked( $options['ignore_admins'] ); ?> />
							<?php esc_html_e( 'Disable tracking for admin users', 'integrate-umami' ); ?>
						</label>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Auto Tracking', 'integrate-umami' ); ?>
					</th>
					<td>
						<label for="integrate_umami_auto_track">
							<input type="checkbox" name="integrate_umami_options[auto_track]" id="integrate_umami_auto_track"
								value="1" <?php checked( $options['auto_track'] ); ?> />
							<?php esc_html_e( 'Automatically track page views and outbound link clicks', 'integrate-umami' ); ?>
							<p class="description">
								<?php
								echo wp_kses(
									__( 'When disabled, you must call <code>umami.track()</code> manually in your theme or plugin code. See <a href="https://umami.is/docs/tracker-functions">Tracker functions</a>.', 'integrate-umami' ),
									array(
										'code' => array(),
										'a'    => array(
											'href' => array(),
										),
									)
								);
								?>
							</p>
						</label>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Track Comment Submit', 'integrate-umami' ); ?>
					</th>
					<td>
						<label for="integrate_umami_track_comments">
							<input type="checkbox" name="integrate_umami_options[track_comments]" id="integrate_umami_track_comments" value="1" <?php checked( $options['track_comments'] ); ?> />
							<?php
							echo wp_kses(
								__( 'Track Comment submits using <a href="https://umami.is/docs/track-events">events</a>', 'integrate-umami' ),
								array(
									'a' => array(
										'href' => array(),
									),
								)
							);
							?>
						</label>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Do Not Track', 'integrate-umami' ); ?>
					</th>
					<td>
						<label for="integrate_umami_do_not_track">
							<input type="checkbox" name="integrate_umami_options[do_not_track]" id="integrate_umami_do_not_track"
								value="1" <?php checked( $options['do_not_track'] ); ?> />
							<?php
							echo wp_kses(
								__( 'Respect visitor`s <b>Do Not Track</b> setting (Not Supported by Umami v2)', 'integrate-umami' ),
								array(
									'b' => array(),
								)
							);
							?>
						</label>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Cache', 'integrate-umami' ); ?>
						<span style="color: #d63638; font-size: 11px; font-weight: normal;"><?php esc_html_e( '(Deprecated)', 'integrate-umami' ); ?></span>
					</th>
					<td>
						<label for="integrate_umami_cache">
							<input type="checkbox" name="integrate_umami_options[cache]" id="integrate_umami_cache"
								value="1" <?php checked( $options['cache'] ); ?> />
							<?php esc_html_e( 'Enable caching of tracking data using session storage', 'integrate-umami' ); ?>
							<p class="description" style="color: #d63638;">
								<?php
								echo wp_kses(
									__( '<b>Deprecated:</b> This option has been removed in Umami v3 and will be removed from this plugin in a future release.', 'integrate-umami' ),
									array(
										'b' => array(),
									)
								);
								?>
							</p>
						</label>
					</td>
				</tr>
				<tr>
					<th class="row">
						<?php esc_html_e( 'Tag', 'integrate-umami' ); ?>
					</th>
					<td>
						<input class="integrate-umami-text" type="text" name="integrate_umami_options[tag]" id="integrate_umami_tag"
							value="<?php echo esc_attr( $options['tag'] ); ?>"/>
						<p class="description">
							<?php
							echo wp_kses(
								__( 'Assign a tag to group tracked events. Useful for A/B testing. See <a href="https://umami.is/docs/tracker-configuration">Tracker configuration</a>.', 'integrate-umami' ),
								array(
									'a' => array(
										'href' => array(),
									),
								)
							);
							?>
						</p>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Domains', 'integrate-umami' ); ?>
					</th>
					<td>
						<input class="integrate-umami-text" type="text" name="integrate_umami_options[domains]" id="integrate_umami_domains"
							value="<?php echo esc_attr( $options['domains'] ); ?>"/>
						<p class="description">
							<?php esc_html_e( 'Comma-separated list of domains where tracking is active. Leave empty to track on all domains.', 'integrate-umami' ); ?>
						</p>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Exclude Search Params', 'integrate-umami' ); ?>
					</th>
					<td>
						<label for="integrate_umami_exclude_search">
							<input type="checkbox" name="integrate_umami_options[exclude_search]" id="integrate_umami_exclude_search"
								value="1" <?php checked( $options['exclude_search'] ); ?> />
							<?php esc_html_e( 'Exclude URL query parameters from tracked page URLs', 'integrate-umami' ); ?>
							<p class="description">
								<?php esc_html_e( 'Removes ?query=string from tracked URLs. Requires Umami v3.', 'integrate-umami' ); ?>
							</p>
						</label>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Exclude Hash', 'integrate-umami' ); ?>
					</th>
					<td>
						<label for="integrate_umami_exclude_hash">
							<input type="checkbox" name="integrate_umami_options[exclude_hash]" id="integrate_umami_exclude_hash"
								value="1" <?php checked( $options['exclude_hash'] ); ?> />
							<?php esc_html_e( 'Exclude URL hash fragments from tracked page URLs', 'integrate-umami' ); ?>
							<p class="description">
								<?php esc_html_e( 'Removes #fragment from tracked URLs. Requires Umami v3.', 'integrate-umami' ); ?>
							</p>
						</label>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Before Send Function', 'integrate-umami' ); ?>
					</th>
					<td>
						<input class="integrate-umami-text" type="text" name="integrate_umami_options[before_send]" id="integrate_umami_before_send"
							value="<?php echo esc_attr( $options['before_send'] ); ?>"/>
						<p class="description">
							<?php
							echo wp_kses(
								__( 'Name of a JavaScript function to intercept tracking data before it is sent. The function receives <code>(type, payload)</code> and should return the modified payload, or a falsy value to cancel the request. Requires Umami v3.', 'integrate-umami' ),
								array(
									'code' => array(),
								)
							);
							?>
						</p>
					</td>
				</tr>
			</table>
		</div>
	</div>

	<div class="integrate-umami-collapsed">
		<input class="toggle" id="api-options" type="checkbox">
		<label class="toggle-label" for="api-options"><?php esc_html_e( 'API Connection (Optional)', 'integrate-umami' ); ?></label>
		<div class="content">
			<p class="description">
				<?php
				echo wp_kses(
					__( 'Connect to the Umami API to display analytics in your WordPress dashboard. For Umami Cloud, use an API key. For self-hosted instances, use your Umami username and password. See <a href="https://umami.is/docs/api">API documentation</a>.', 'integrate-umami' ),
					array(
						'a' => array(
							'href' => array(),
						),
					)
				);
				?>
			</p>
			<table class="form-table">
				<tr>
					<th class="row">
						<?php esc_html_e( 'API Key', 'integrate-umami' ); ?>
					</th>
					<td>
						<input class="integrate-umami-text" type="password" name="integrate_umami_options[api_key]" id="integrate_umami_api_key"
							value="<?php echo esc_attr( $options['api_key'] ); ?>" autocomplete="off"/>
						<p class="description">
							<?php
							echo wp_kses(
								__( 'For Umami Cloud: create an API key at Settings &gt; API Keys in your <a href="https://cloud.umami.is">Umami Cloud</a> dashboard.', 'integrate-umami' ),
								array(
									'a' => array(
										'href' => array(),
									),
								)
							);
							?>
						</p>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'API Username', 'integrate-umami' ); ?>
					</th>
					<td>
						<input class="integrate-umami-text" type="text" name="integrate_umami_options[api_username]" id="integrate_umami_api_username"
							value="<?php echo esc_attr( $options['api_username'] ); ?>" autocomplete="off"/>
						<p class="description">
							<?php esc_html_e( 'For self-hosted Umami: your Umami admin username.', 'integrate-umami' ); ?>
						</p>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'API Password', 'integrate-umami' ); ?>
					</th>
					<td>
						<input class="integrate-umami-text" type="password" name="integrate_umami_options[api_password]" id="integrate_umami_api_password"
							value="<?php echo esc_attr( $options['api_password'] ); ?>" autocomplete="off"/>
						<p class="description">
							<?php esc_html_e( 'For self-hosted Umami: your Umami admin password.', 'integrate-umami' ); ?>
						</p>
					</td>
				</tr>
			</table>
		</div>
	</div>

	<?php submit_button(); ?>
</form>
