name: WPCS check

on: pull_request

jobs:
  phpcs:
    name: PHP CS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WP CS Check
        uses: 10up/wpcs-action@stable