name: Linting

on: pull_request

jobs:
  phpcs:
    name: PHP CS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Check installed cs rules
        run: vendor/bin/phpcs -i
      - name: CS Check
        run: ./vendor/bin/phpcs --runtime-set ignore_warnings_on_exit true --standard=phpcs.xml ./
