name: Playwright Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wpVersion: [ '6.4', '6.5', '6.6' ]
        phpVersion: [ '8.0', '8.1', '8.2' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP with no coverage driver
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.phpVersion }}
        coverage: none
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: |
        composer install --no-progress --no-dev
        npm ci
        WP_ENV_CORE=wordpress/wordpress#${{ matrix.wpVersion }} WP_ENV_PHP_VERSION=${{ matrix.phpVersion }} npm run env start
    - name: Install Playwright Browsers
      run: npx playwright install chromium
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
