name: Pull Request Checks
on:
  pull_request:
    branches: [ main ]
jobs:
  linting:
    name: PHP CS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Check installed cs rules
        run: vendor/bin/phpcs -i
      - name: CS Check
        run: ./vendor/bin/phpcs --runtime-set ignore_warnings_on_exit true --standard=phpcs.xml ./

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wpVersion: [ '6.7', '6.8', '6.8.1', '6.8.2', '6.8.3' ]
        phpVersion: [ '8.1', '8.2', '8.3', '8.4' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP with no coverage driver
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.phpVersion }}
        coverage: none
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: |
        composer install --no-progress --no-dev
        npm ci
        WP_ENV_CORE=wordpress/wordpress#${{ matrix.wpVersion }} WP_ENV_PHP_VERSION=${{ matrix.phpVersion }} npm run env start
    - name: Install Playwright Browsers
      run: npx playwright install chromium
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  automerge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    needs:
      - linting
      - test
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: patch
          github-token: ${{ secrets.PAT_TOKEN }}

